version: "3"

services:
  email-tracker:
    image: wrfly/et:latest
    restart: unless-stopped
    ports:
      - 8080:2020
    environment:
      - ET_DEBUG=true
      - ET_SendGridAPI=""
    volumes:
      - /tmp/et-data:/data
